#!/bin/sh
#  Copyright (c) Hubert Bukowski. All rights reserved.
#  Licensed under the MIT License.
#  See LICENSE file in the project root for full license information.

current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$current_branch" = "main" ]; then
	pnpm verify
fi
